/**
 * This class is generated by jOOQ
 */
package com.iks.data.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * Tabla de la cabera del proceso de las operaciones de conexion para el sistema 
 * ARCH
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CabeceraIkasRecord extends org.jooq.impl.UpdatableRecordImpl<com.iks.data.jooq.tables.records.CabeceraIkasRecord> implements org.jooq.Record7<java.lang.Integer, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp> {

	private static final long serialVersionUID = 340593195;

	/**
	 * Setter for <code>ikas.cabecera_ikas.idcabecera_ikas</code>.
	 */
	public void setIdcabeceraIkas(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ikas.cabecera_ikas.idcabecera_ikas</code>.
	 */
	public java.lang.Integer getIdcabeceraIkas() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>ikas.cabecera_ikas.fecha_carga</code>.
	 */
	public void setFechaCarga(java.sql.Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ikas.cabecera_ikas.fecha_carga</code>.
	 */
	public java.sql.Timestamp getFechaCarga() {
		return (java.sql.Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>ikas.cabecera_ikas.estado_cabecera</code>.
	 */
	public void setEstadoCabecera(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ikas.cabecera_ikas.estado_cabecera</code>.
	 */
	public java.lang.String getEstadoCabecera() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>ikas.cabecera_ikas.id_usuario</code>.
	 */
	public void setIdUsuario(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ikas.cabecera_ikas.id_usuario</code>.
	 */
	public java.lang.Integer getIdUsuario() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>ikas.cabecera_ikas.id_empresa</code>.
	 */
	public void setIdEmpresa(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ikas.cabecera_ikas.id_empresa</code>.
	 */
	public java.lang.Integer getIdEmpresa() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>ikas.cabecera_ikas.id_tipo_operacion</code>.
	 */
	public void setIdTipoOperacion(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ikas.cabecera_ikas.id_tipo_operacion</code>.
	 */
	public java.lang.Integer getIdTipoOperacion() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>ikas.cabecera_ikas.fecha_proceso</code>.
	 */
	public void setFechaProceso(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ikas.cabecera_ikas.fecha_proceso</code>.
	 */
	public java.sql.Timestamp getFechaProceso() {
		return (java.sql.Timestamp) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.iks.data.jooq.tables.CabeceraIkas.CABECERA_IKAS.IDCABECERA_IKAS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field2() {
		return com.iks.data.jooq.tables.CabeceraIkas.CABECERA_IKAS.FECHA_CARGA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.iks.data.jooq.tables.CabeceraIkas.CABECERA_IKAS.ESTADO_CABECERA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.iks.data.jooq.tables.CabeceraIkas.CABECERA_IKAS.ID_USUARIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.iks.data.jooq.tables.CabeceraIkas.CABECERA_IKAS.ID_EMPRESA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return com.iks.data.jooq.tables.CabeceraIkas.CABECERA_IKAS.ID_TIPO_OPERACION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return com.iks.data.jooq.tables.CabeceraIkas.CABECERA_IKAS.FECHA_PROCESO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIdcabeceraIkas();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value2() {
		return getFechaCarga();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getEstadoCabecera();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getIdUsuario();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getIdEmpresa();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getIdTipoOperacion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getFechaProceso();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CabeceraIkasRecord value1(java.lang.Integer value) {
		setIdcabeceraIkas(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CabeceraIkasRecord value2(java.sql.Timestamp value) {
		setFechaCarga(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CabeceraIkasRecord value3(java.lang.String value) {
		setEstadoCabecera(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CabeceraIkasRecord value4(java.lang.Integer value) {
		setIdUsuario(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CabeceraIkasRecord value5(java.lang.Integer value) {
		setIdEmpresa(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CabeceraIkasRecord value6(java.lang.Integer value) {
		setIdTipoOperacion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CabeceraIkasRecord value7(java.sql.Timestamp value) {
		setFechaProceso(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CabeceraIkasRecord values(java.lang.Integer value1, java.sql.Timestamp value2, java.lang.String value3, java.lang.Integer value4, java.lang.Integer value5, java.lang.Integer value6, java.sql.Timestamp value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CabeceraIkasRecord
	 */
	public CabeceraIkasRecord() {
		super(com.iks.data.jooq.tables.CabeceraIkas.CABECERA_IKAS);
	}

	/**
	 * Create a detached, initialised CabeceraIkasRecord
	 */
	public CabeceraIkasRecord(java.lang.Integer idcabeceraIkas, java.sql.Timestamp fechaCarga, java.lang.String estadoCabecera, java.lang.Integer idUsuario, java.lang.Integer idEmpresa, java.lang.Integer idTipoOperacion, java.sql.Timestamp fechaProceso) {
		super(com.iks.data.jooq.tables.CabeceraIkas.CABECERA_IKAS);

		setValue(0, idcabeceraIkas);
		setValue(1, fechaCarga);
		setValue(2, estadoCabecera);
		setValue(3, idUsuario);
		setValue(4, idEmpresa);
		setValue(5, idTipoOperacion);
		setValue(6, fechaProceso);
	}
}
