/**
 * This class is generated by jOOQ
 */
package com.iks.data.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * Esta tabla almacena el historial de anulaciones
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DetalleAnulacionRecord extends org.jooq.impl.UpdatableRecordImpl<com.iks.data.jooq.tables.records.DetalleAnulacionRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 144130893;

	/**
	 * Setter for <code>ikas.detalle_anulacion.iddetalle_anulacion</code>.
	 */
	public void setIddetalleAnulacion(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ikas.detalle_anulacion.iddetalle_anulacion</code>.
	 */
	public java.lang.Integer getIddetalleAnulacion() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>ikas.detalle_anulacion.id_detalle</code>.
	 */
	public void setIdDetalle(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ikas.detalle_anulacion.id_detalle</code>.
	 */
	public java.lang.Integer getIdDetalle() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>ikas.detalle_anulacion.id_empresa</code>.
	 */
	public void setIdEmpresa(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ikas.detalle_anulacion.id_empresa</code>.
	 */
	public java.lang.Integer getIdEmpresa() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.iks.data.jooq.tables.DetalleAnulacion.DETALLE_ANULACION.IDDETALLE_ANULACION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.iks.data.jooq.tables.DetalleAnulacion.DETALLE_ANULACION.ID_DETALLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.iks.data.jooq.tables.DetalleAnulacion.DETALLE_ANULACION.ID_EMPRESA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIddetalleAnulacion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getIdDetalle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getIdEmpresa();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleAnulacionRecord value1(java.lang.Integer value) {
		setIddetalleAnulacion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleAnulacionRecord value2(java.lang.Integer value) {
		setIdDetalle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleAnulacionRecord value3(java.lang.Integer value) {
		setIdEmpresa(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleAnulacionRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DetalleAnulacionRecord
	 */
	public DetalleAnulacionRecord() {
		super(com.iks.data.jooq.tables.DetalleAnulacion.DETALLE_ANULACION);
	}

	/**
	 * Create a detached, initialised DetalleAnulacionRecord
	 */
	public DetalleAnulacionRecord(java.lang.Integer iddetalleAnulacion, java.lang.Integer idDetalle, java.lang.Integer idEmpresa) {
		super(com.iks.data.jooq.tables.DetalleAnulacion.DETALLE_ANULACION);

		setValue(0, iddetalleAnulacion);
		setValue(1, idDetalle);
		setValue(2, idEmpresa);
	}
}
