/**
 * This class is generated by jOOQ
 */
package com.iks.data.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * Tabla que almacena los detalles de la operacion denominada TRANSACION
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DetalleTransaccionRecord extends org.jooq.impl.UpdatableRecordImpl<com.iks.data.jooq.tables.records.DetalleTransaccionRecord> implements org.jooq.Record15<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Double, java.sql.Date, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Double, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 35484944;

	/**
	 * Setter for <code>ikas.detalle_transaccion.id_det_transaccion</code>.
	 */
	public void setIdDetTransaccion(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ikas.detalle_transaccion.id_det_transaccion</code>.
	 */
	public java.lang.Integer getIdDetTransaccion() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>ikas.detalle_transaccion.secuencial</code>.
	 */
	public void setSecuencial(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ikas.detalle_transaccion.secuencial</code>.
	 */
	public java.lang.String getSecuencial() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>ikas.detalle_transaccion.terminal</code>.
	 */
	public void setTerminal(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ikas.detalle_transaccion.terminal</code>.
	 */
	public java.lang.String getTerminal() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>ikas.detalle_transaccion.numero_confirmacion</code>.
	 */
	public void setNumeroConfirmacion(java.lang.Double value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ikas.detalle_transaccion.numero_confirmacion</code>.
	 */
	public java.lang.Double getNumeroConfirmacion() {
		return (java.lang.Double) getValue(3);
	}

	/**
	 * Setter for <code>ikas.detalle_transaccion.fecha</code>.
	 */
	public void setFecha(java.sql.Date value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ikas.detalle_transaccion.fecha</code>.
	 */
	public java.sql.Date getFecha() {
		return (java.sql.Date) getValue(4);
	}

	/**
	 * Setter for <code>ikas.detalle_transaccion.tipo</code>.
	 */
	public void setTipo(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ikas.detalle_transaccion.tipo</code>.
	 */
	public java.lang.String getTipo() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>ikas.detalle_transaccion.id_empresa</code>.
	 */
	public void setIdEmpresa(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ikas.detalle_transaccion.id_empresa</code>.
	 */
	public java.lang.Integer getIdEmpresa() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>ikas.detalle_transaccion.contraparte</code>.
	 */
	public void setContraparte(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ikas.detalle_transaccion.contraparte</code>.
	 */
	public java.lang.String getContraparte() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>ikas.detalle_transaccion.cod_producto</code>.
	 */
	public void setCodProducto(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ikas.detalle_transaccion.cod_producto</code>.
	 */
	public java.lang.String getCodProducto() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>ikas.detalle_transaccion.cantidad</code>.
	 */
	public void setCantidad(java.lang.Double value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ikas.detalle_transaccion.cantidad</code>.
	 */
	public java.lang.Double getCantidad() {
		return (java.lang.Double) getValue(9);
	}

	/**
	 * Setter for <code>ikas.detalle_transaccion.tipo_transporte</code>.
	 */
	public void setTipoTransporte(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ikas.detalle_transaccion.tipo_transporte</code>.
	 */
	public java.lang.String getTipoTransporte() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>ikas.detalle_transaccion.cedula_chofer</code>.
	 */
	public void setCedulaChofer(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>ikas.detalle_transaccion.cedula_chofer</code>.
	 */
	public java.lang.String getCedulaChofer() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>ikas.detalle_transaccion.placa</code>.
	 */
	public void setPlaca(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>ikas.detalle_transaccion.placa</code>.
	 */
	public java.lang.String getPlaca() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>ikas.detalle_transaccion.guia_remision</code>.
	 */
	public void setGuiaRemision(java.lang.String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>ikas.detalle_transaccion.guia_remision</code>.
	 */
	public java.lang.String getGuiaRemision() {
		return (java.lang.String) getValue(13);
	}

	/**
	 * Setter for <code>ikas.detalle_transaccion.id_cabacera</code>.
	 */
	public void setIdCabacera(java.lang.Integer value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>ikas.detalle_transaccion.id_cabacera</code>.
	 */
	public java.lang.Integer getIdCabacera() {
		return (java.lang.Integer) getValue(14);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record15 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row15<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Double, java.sql.Date, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Double, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row15) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row15<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Double, java.sql.Date, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Double, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row15) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION.ID_DET_TRANSACCION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION.SECUENCIAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION.TERMINAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field4() {
		return com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION.NUMERO_CONFIRMACION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field5() {
		return com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION.FECHA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION.TIPO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION.ID_EMPRESA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION.CONTRAPARTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION.COD_PRODUCTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field10() {
		return com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION.CANTIDAD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION.TIPO_TRANSPORTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION.CEDULA_CHOFER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field13() {
		return com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION.PLACA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field14() {
		return com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION.GUIA_REMISION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field15() {
		return com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION.ID_CABACERA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIdDetTransaccion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getSecuencial();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getTerminal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value4() {
		return getNumeroConfirmacion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value5() {
		return getFecha();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getTipo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getIdEmpresa();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getContraparte();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getCodProducto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value10() {
		return getCantidad();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getTipoTransporte();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getCedulaChofer();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value13() {
		return getPlaca();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value14() {
		return getGuiaRemision();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value15() {
		return getIdCabacera();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleTransaccionRecord value1(java.lang.Integer value) {
		setIdDetTransaccion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleTransaccionRecord value2(java.lang.String value) {
		setSecuencial(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleTransaccionRecord value3(java.lang.String value) {
		setTerminal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleTransaccionRecord value4(java.lang.Double value) {
		setNumeroConfirmacion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleTransaccionRecord value5(java.sql.Date value) {
		setFecha(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleTransaccionRecord value6(java.lang.String value) {
		setTipo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleTransaccionRecord value7(java.lang.Integer value) {
		setIdEmpresa(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleTransaccionRecord value8(java.lang.String value) {
		setContraparte(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleTransaccionRecord value9(java.lang.String value) {
		setCodProducto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleTransaccionRecord value10(java.lang.Double value) {
		setCantidad(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleTransaccionRecord value11(java.lang.String value) {
		setTipoTransporte(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleTransaccionRecord value12(java.lang.String value) {
		setCedulaChofer(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleTransaccionRecord value13(java.lang.String value) {
		setPlaca(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleTransaccionRecord value14(java.lang.String value) {
		setGuiaRemision(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleTransaccionRecord value15(java.lang.Integer value) {
		setIdCabacera(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleTransaccionRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.Double value4, java.sql.Date value5, java.lang.String value6, java.lang.Integer value7, java.lang.String value8, java.lang.String value9, java.lang.Double value10, java.lang.String value11, java.lang.String value12, java.lang.String value13, java.lang.String value14, java.lang.Integer value15) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DetalleTransaccionRecord
	 */
	public DetalleTransaccionRecord() {
		super(com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION);
	}

	/**
	 * Create a detached, initialised DetalleTransaccionRecord
	 */
	public DetalleTransaccionRecord(java.lang.Integer idDetTransaccion, java.lang.String secuencial, java.lang.String terminal, java.lang.Double numeroConfirmacion, java.sql.Date fecha, java.lang.String tipo, java.lang.Integer idEmpresa, java.lang.String contraparte, java.lang.String codProducto, java.lang.Double cantidad, java.lang.String tipoTransporte, java.lang.String cedulaChofer, java.lang.String placa, java.lang.String guiaRemision, java.lang.Integer idCabacera) {
		super(com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION);

		setValue(0, idDetTransaccion);
		setValue(1, secuencial);
		setValue(2, terminal);
		setValue(3, numeroConfirmacion);
		setValue(4, fecha);
		setValue(5, tipo);
		setValue(6, idEmpresa);
		setValue(7, contraparte);
		setValue(8, codProducto);
		setValue(9, cantidad);
		setValue(10, tipoTransporte);
		setValue(11, cedulaChofer);
		setValue(12, placa);
		setValue(13, guiaRemision);
		setValue(14, idCabacera);
	}
}
