/**
 * This class is generated by jOOQ
 */
package com.iks.data.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * Tabla de las transacciones de la operacion denominada como Venta GAS
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DetalleVentaGasRecord extends org.jooq.impl.UpdatableRecordImpl<com.iks.data.jooq.tables.records.DetalleVentaGasRecord> implements org.jooq.Record8<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Double, java.sql.Date, java.lang.Integer, java.lang.String, java.lang.Double> {

	private static final long serialVersionUID = 749973509;

	/**
	 * Setter for <code>ikas.detalle_venta_gas.id_detalle_venta_gas</code>.
	 */
	public void setIdDetalleVentaGas(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ikas.detalle_venta_gas.id_detalle_venta_gas</code>.
	 */
	public java.lang.Integer getIdDetalleVentaGas() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>ikas.detalle_venta_gas.id_cabecera</code>.
	 */
	public void setIdCabecera(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ikas.detalle_venta_gas.id_cabecera</code>.
	 */
	public java.lang.Integer getIdCabecera() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>ikas.detalle_venta_gas.terminal</code>.
	 */
	public void setTerminal(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ikas.detalle_venta_gas.terminal</code>.
	 */
	public java.lang.String getTerminal() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>ikas.detalle_venta_gas.numeroConfirmacion</code>.
	 */
	public void setNumeroconfirmacion(java.lang.Double value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ikas.detalle_venta_gas.numeroConfirmacion</code>.
	 */
	public java.lang.Double getNumeroconfirmacion() {
		return (java.lang.Double) getValue(3);
	}

	/**
	 * Setter for <code>ikas.detalle_venta_gas.fecha</code>.
	 */
	public void setFecha(java.sql.Date value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ikas.detalle_venta_gas.fecha</code>.
	 */
	public java.sql.Date getFecha() {
		return (java.sql.Date) getValue(4);
	}

	/**
	 * Setter for <code>ikas.detalle_venta_gas.id_empresa</code>.
	 */
	public void setIdEmpresa(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ikas.detalle_venta_gas.id_empresa</code>.
	 */
	public java.lang.Integer getIdEmpresa() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>ikas.detalle_venta_gas.codProducto</code>.
	 */
	public void setCodproducto(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ikas.detalle_venta_gas.codProducto</code>.
	 */
	public java.lang.String getCodproducto() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>ikas.detalle_venta_gas.cantidad</code>.
	 */
	public void setCantidad(java.lang.Double value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ikas.detalle_venta_gas.cantidad</code>.
	 */
	public java.lang.Double getCantidad() {
		return (java.lang.Double) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Double, java.sql.Date, java.lang.Integer, java.lang.String, java.lang.Double> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Double, java.sql.Date, java.lang.Integer, java.lang.String, java.lang.Double> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.iks.data.jooq.tables.DetalleVentaGas.DETALLE_VENTA_GAS.ID_DETALLE_VENTA_GAS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.iks.data.jooq.tables.DetalleVentaGas.DETALLE_VENTA_GAS.ID_CABECERA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.iks.data.jooq.tables.DetalleVentaGas.DETALLE_VENTA_GAS.TERMINAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field4() {
		return com.iks.data.jooq.tables.DetalleVentaGas.DETALLE_VENTA_GAS.NUMEROCONFIRMACION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field5() {
		return com.iks.data.jooq.tables.DetalleVentaGas.DETALLE_VENTA_GAS.FECHA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return com.iks.data.jooq.tables.DetalleVentaGas.DETALLE_VENTA_GAS.ID_EMPRESA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.iks.data.jooq.tables.DetalleVentaGas.DETALLE_VENTA_GAS.CODPRODUCTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field8() {
		return com.iks.data.jooq.tables.DetalleVentaGas.DETALLE_VENTA_GAS.CANTIDAD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIdDetalleVentaGas();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getIdCabecera();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getTerminal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value4() {
		return getNumeroconfirmacion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value5() {
		return getFecha();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getIdEmpresa();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getCodproducto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value8() {
		return getCantidad();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleVentaGasRecord value1(java.lang.Integer value) {
		setIdDetalleVentaGas(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleVentaGasRecord value2(java.lang.Integer value) {
		setIdCabecera(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleVentaGasRecord value3(java.lang.String value) {
		setTerminal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleVentaGasRecord value4(java.lang.Double value) {
		setNumeroconfirmacion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleVentaGasRecord value5(java.sql.Date value) {
		setFecha(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleVentaGasRecord value6(java.lang.Integer value) {
		setIdEmpresa(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleVentaGasRecord value7(java.lang.String value) {
		setCodproducto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleVentaGasRecord value8(java.lang.Double value) {
		setCantidad(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DetalleVentaGasRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.String value3, java.lang.Double value4, java.sql.Date value5, java.lang.Integer value6, java.lang.String value7, java.lang.Double value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DetalleVentaGasRecord
	 */
	public DetalleVentaGasRecord() {
		super(com.iks.data.jooq.tables.DetalleVentaGas.DETALLE_VENTA_GAS);
	}

	/**
	 * Create a detached, initialised DetalleVentaGasRecord
	 */
	public DetalleVentaGasRecord(java.lang.Integer idDetalleVentaGas, java.lang.Integer idCabecera, java.lang.String terminal, java.lang.Double numeroconfirmacion, java.sql.Date fecha, java.lang.Integer idEmpresa, java.lang.String codproducto, java.lang.Double cantidad) {
		super(com.iks.data.jooq.tables.DetalleVentaGas.DETALLE_VENTA_GAS);

		setValue(0, idDetalleVentaGas);
		setValue(1, idCabecera);
		setValue(2, terminal);
		setValue(3, numeroconfirmacion);
		setValue(4, fecha);
		setValue(5, idEmpresa);
		setValue(6, codproducto);
		setValue(7, cantidad);
	}
}
