/**
 * This class is generated by jOOQ
 */
package com.iks.data.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * tabla de auditoria del sistema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LogAuditoriaRecord extends org.jooq.impl.UpdatableRecordImpl<com.iks.data.jooq.tables.records.LogAuditoriaRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.Integer> {

	private static final long serialVersionUID = -241930309;

	/**
	 * Setter for <code>ikas.log_auditoria.idlog_auditoria</code>.
	 */
	public void setIdlogAuditoria(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ikas.log_auditoria.idlog_auditoria</code>.
	 */
	public java.lang.Integer getIdlogAuditoria() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>ikas.log_auditoria.id_usuario</code>.
	 */
	public void setIdUsuario(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ikas.log_auditoria.id_usuario</code>.
	 */
	public java.lang.Integer getIdUsuario() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>ikas.log_auditoria.id_row</code>.
	 */
	public void setIdRow(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ikas.log_auditoria.id_row</code>.
	 */
	public java.lang.String getIdRow() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>ikas.log_auditoria.fecha_log</code>.
	 */
	public void setFechaLog(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ikas.log_auditoria.fecha_log</code>.
	 */
	public java.sql.Timestamp getFechaLog() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>ikas.log_auditoria.id_tipo_operacion</code>.
	 */
	public void setIdTipoOperacion(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ikas.log_auditoria.id_tipo_operacion</code>.
	 */
	public java.lang.Integer getIdTipoOperacion() {
		return (java.lang.Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.Integer> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.iks.data.jooq.tables.LogAuditoria.LOG_AUDITORIA.IDLOG_AUDITORIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.iks.data.jooq.tables.LogAuditoria.LOG_AUDITORIA.ID_USUARIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.iks.data.jooq.tables.LogAuditoria.LOG_AUDITORIA.ID_ROW;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return com.iks.data.jooq.tables.LogAuditoria.LOG_AUDITORIA.FECHA_LOG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.iks.data.jooq.tables.LogAuditoria.LOG_AUDITORIA.ID_TIPO_OPERACION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIdlogAuditoria();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getIdUsuario();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getIdRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getFechaLog();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getIdTipoOperacion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LogAuditoriaRecord value1(java.lang.Integer value) {
		setIdlogAuditoria(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LogAuditoriaRecord value2(java.lang.Integer value) {
		setIdUsuario(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LogAuditoriaRecord value3(java.lang.String value) {
		setIdRow(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LogAuditoriaRecord value4(java.sql.Timestamp value) {
		setFechaLog(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LogAuditoriaRecord value5(java.lang.Integer value) {
		setIdTipoOperacion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LogAuditoriaRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.String value3, java.sql.Timestamp value4, java.lang.Integer value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LogAuditoriaRecord
	 */
	public LogAuditoriaRecord() {
		super(com.iks.data.jooq.tables.LogAuditoria.LOG_AUDITORIA);
	}

	/**
	 * Create a detached, initialised LogAuditoriaRecord
	 */
	public LogAuditoriaRecord(java.lang.Integer idlogAuditoria, java.lang.Integer idUsuario, java.lang.String idRow, java.sql.Timestamp fechaLog, java.lang.Integer idTipoOperacion) {
		super(com.iks.data.jooq.tables.LogAuditoria.LOG_AUDITORIA);

		setValue(0, idlogAuditoria);
		setValue(1, idUsuario);
		setValue(2, idRow);
		setValue(3, fechaLog);
		setValue(4, idTipoOperacion);
	}
}
