/**
 * This class is generated by jOOQ
 */
package com.iks.data.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * Tabla q almacena los tipos de operaciones del sistema arch
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TipoOperacionRecord extends org.jooq.impl.UpdatableRecordImpl<com.iks.data.jooq.tables.records.TipoOperacionRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1902841155;

	/**
	 * Setter for <code>ikas.tipo_operacion.idtipo_operacion</code>.
	 */
	public void setIdtipoOperacion(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ikas.tipo_operacion.idtipo_operacion</code>.
	 */
	public java.lang.Integer getIdtipoOperacion() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>ikas.tipo_operacion.nombre</code>.
	 */
	public void setNombre(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ikas.tipo_operacion.nombre</code>.
	 */
	public java.lang.String getNombre() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>ikas.tipo_operacion.descripcion</code>.
	 */
	public void setDescripcion(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ikas.tipo_operacion.descripcion</code>.
	 */
	public java.lang.String getDescripcion() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>ikas.tipo_operacion.estado</code>.
	 */
	public void setEstado(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ikas.tipo_operacion.estado</code>.
	 */
	public java.lang.String getEstado() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.iks.data.jooq.tables.TipoOperacion.TIPO_OPERACION.IDTIPO_OPERACION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.iks.data.jooq.tables.TipoOperacion.TIPO_OPERACION.NOMBRE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.iks.data.jooq.tables.TipoOperacion.TIPO_OPERACION.DESCRIPCION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.iks.data.jooq.tables.TipoOperacion.TIPO_OPERACION.ESTADO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIdtipoOperacion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getNombre();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDescripcion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getEstado();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TipoOperacionRecord value1(java.lang.Integer value) {
		setIdtipoOperacion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TipoOperacionRecord value2(java.lang.String value) {
		setNombre(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TipoOperacionRecord value3(java.lang.String value) {
		setDescripcion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TipoOperacionRecord value4(java.lang.String value) {
		setEstado(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TipoOperacionRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TipoOperacionRecord
	 */
	public TipoOperacionRecord() {
		super(com.iks.data.jooq.tables.TipoOperacion.TIPO_OPERACION);
	}

	/**
	 * Create a detached, initialised TipoOperacionRecord
	 */
	public TipoOperacionRecord(java.lang.Integer idtipoOperacion, java.lang.String nombre, java.lang.String descripcion, java.lang.String estado) {
		super(com.iks.data.jooq.tables.TipoOperacion.TIPO_OPERACION);

		setValue(0, idtipoOperacion);
		setValue(1, nombre);
		setValue(2, descripcion);
		setValue(3, estado);
	}
}
