/**
 * This class is generated by jOOQ
 */
package com.iks.data.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * Tabla de los usuarios del sistema iKas
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsuariosRecord extends org.jooq.impl.UpdatableRecordImpl<com.iks.data.jooq.tables.records.UsuariosRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String, java.lang.String, byte[], java.lang.String> {

	private static final long serialVersionUID = 1312017117;

	/**
	 * Setter for <code>ikas.usuarios.id_user</code>.
	 */
	public void setIdUser(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ikas.usuarios.id_user</code>.
	 */
	public java.lang.Integer getIdUser() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>ikas.usuarios.nombre</code>.
	 */
	public void setNombre(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ikas.usuarios.nombre</code>.
	 */
	public java.lang.String getNombre() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>ikas.usuarios.nickname</code>.
	 */
	public void setNickname(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ikas.usuarios.nickname</code>.
	 */
	public java.lang.String getNickname() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>ikas.usuarios.password</code>.
	 */
	public void setPassword(byte[] value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ikas.usuarios.password</code>.
	 */
	public byte[] getPassword() {
		return (byte[]) getValue(3);
	}

	/**
	 * Setter for <code>ikas.usuarios.estado</code>.
	 */
	public void setEstado(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ikas.usuarios.estado</code>.
	 */
	public java.lang.String getEstado() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, byte[], java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, byte[], java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.iks.data.jooq.tables.Usuarios.USUARIOS.ID_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.iks.data.jooq.tables.Usuarios.USUARIOS.NOMBRE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.iks.data.jooq.tables.Usuarios.USUARIOS.NICKNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field4() {
		return com.iks.data.jooq.tables.Usuarios.USUARIOS.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.iks.data.jooq.tables.Usuarios.USUARIOS.ESTADO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIdUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getNombre();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getNickname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value4() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getEstado();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuariosRecord value1(java.lang.Integer value) {
		setIdUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuariosRecord value2(java.lang.String value) {
		setNombre(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuariosRecord value3(java.lang.String value) {
		setNickname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuariosRecord value4(byte[] value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuariosRecord value5(java.lang.String value) {
		setEstado(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuariosRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, byte[] value4, java.lang.String value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsuariosRecord
	 */
	public UsuariosRecord() {
		super(com.iks.data.jooq.tables.Usuarios.USUARIOS);
	}

	/**
	 * Create a detached, initialised UsuariosRecord
	 */
	public UsuariosRecord(java.lang.Integer idUser, java.lang.String nombre, java.lang.String nickname, byte[] password, java.lang.String estado) {
		super(com.iks.data.jooq.tables.Usuarios.USUARIOS);

		setValue(0, idUser);
		setValue(1, nombre);
		setValue(2, nickname);
		setValue(3, password);
		setValue(4, estado);
	}
}
