/**
 * This class is generated by jOOQ
 */
package com.iks.data.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ikas extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1569669290;

	/**
	 * The singleton instance of <code>ikas</code>
	 */
	public static final Ikas IKAS = new Ikas();

	/**
	 * No further instances allowed
	 */
	private Ikas() {
		super("ikas");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.iks.data.jooq.tables.CabeceraIkas.CABECERA_IKAS,
			com.iks.data.jooq.tables.DetalleAnulacion.DETALLE_ANULACION,
			com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION,
			com.iks.data.jooq.tables.DetalleVentaGas.DETALLE_VENTA_GAS,
			com.iks.data.jooq.tables.Empresas.EMPRESAS,
			com.iks.data.jooq.tables.LogAuditoria.LOG_AUDITORIA,
			com.iks.data.jooq.tables.TipoOperacion.TIPO_OPERACION,
			com.iks.data.jooq.tables.Usuarios.USUARIOS);
	}
}
