/**
 * This class is generated by jOOQ
 */
package com.iks.data.jooq;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>ikas</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.iks.data.jooq.tables.records.CabeceraIkasRecord, java.lang.Integer> IDENTITY_CABECERA_IKAS = Identities0.IDENTITY_CABECERA_IKAS;
	public static final org.jooq.Identity<com.iks.data.jooq.tables.records.DetalleAnulacionRecord, java.lang.Integer> IDENTITY_DETALLE_ANULACION = Identities0.IDENTITY_DETALLE_ANULACION;
	public static final org.jooq.Identity<com.iks.data.jooq.tables.records.DetalleTransaccionRecord, java.lang.Integer> IDENTITY_DETALLE_TRANSACCION = Identities0.IDENTITY_DETALLE_TRANSACCION;
	public static final org.jooq.Identity<com.iks.data.jooq.tables.records.DetalleVentaGasRecord, java.lang.Integer> IDENTITY_DETALLE_VENTA_GAS = Identities0.IDENTITY_DETALLE_VENTA_GAS;
	public static final org.jooq.Identity<com.iks.data.jooq.tables.records.EmpresasRecord, java.lang.Integer> IDENTITY_EMPRESAS = Identities0.IDENTITY_EMPRESAS;
	public static final org.jooq.Identity<com.iks.data.jooq.tables.records.LogAuditoriaRecord, java.lang.Integer> IDENTITY_LOG_AUDITORIA = Identities0.IDENTITY_LOG_AUDITORIA;
	public static final org.jooq.Identity<com.iks.data.jooq.tables.records.TipoOperacionRecord, java.lang.Integer> IDENTITY_TIPO_OPERACION = Identities0.IDENTITY_TIPO_OPERACION;
	public static final org.jooq.Identity<com.iks.data.jooq.tables.records.UsuariosRecord, java.lang.Integer> IDENTITY_USUARIOS = Identities0.IDENTITY_USUARIOS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.iks.data.jooq.tables.records.CabeceraIkasRecord> KEY_CABECERA_IKAS_PRIMARY = UniqueKeys0.KEY_CABECERA_IKAS_PRIMARY;
	public static final org.jooq.UniqueKey<com.iks.data.jooq.tables.records.DetalleAnulacionRecord> KEY_DETALLE_ANULACION_PRIMARY = UniqueKeys0.KEY_DETALLE_ANULACION_PRIMARY;
	public static final org.jooq.UniqueKey<com.iks.data.jooq.tables.records.DetalleTransaccionRecord> KEY_DETALLE_TRANSACCION_PRIMARY = UniqueKeys0.KEY_DETALLE_TRANSACCION_PRIMARY;
	public static final org.jooq.UniqueKey<com.iks.data.jooq.tables.records.DetalleVentaGasRecord> KEY_DETALLE_VENTA_GAS_PRIMARY = UniqueKeys0.KEY_DETALLE_VENTA_GAS_PRIMARY;
	public static final org.jooq.UniqueKey<com.iks.data.jooq.tables.records.EmpresasRecord> KEY_EMPRESAS_PRIMARY = UniqueKeys0.KEY_EMPRESAS_PRIMARY;
	public static final org.jooq.UniqueKey<com.iks.data.jooq.tables.records.LogAuditoriaRecord> KEY_LOG_AUDITORIA_PRIMARY = UniqueKeys0.KEY_LOG_AUDITORIA_PRIMARY;
	public static final org.jooq.UniqueKey<com.iks.data.jooq.tables.records.TipoOperacionRecord> KEY_TIPO_OPERACION_PRIMARY = UniqueKeys0.KEY_TIPO_OPERACION_PRIMARY;
	public static final org.jooq.UniqueKey<com.iks.data.jooq.tables.records.UsuariosRecord> KEY_USUARIOS_PRIMARY = UniqueKeys0.KEY_USUARIOS_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.iks.data.jooq.tables.records.CabeceraIkasRecord, com.iks.data.jooq.tables.records.UsuariosRecord> CI_FK_USR = ForeignKeys0.CI_FK_USR;
	public static final org.jooq.ForeignKey<com.iks.data.jooq.tables.records.CabeceraIkasRecord, com.iks.data.jooq.tables.records.EmpresasRecord> CI_FK_EMP = ForeignKeys0.CI_FK_EMP;
	public static final org.jooq.ForeignKey<com.iks.data.jooq.tables.records.CabeceraIkasRecord, com.iks.data.jooq.tables.records.TipoOperacionRecord> CI_FK_TPO = ForeignKeys0.CI_FK_TPO;
	public static final org.jooq.ForeignKey<com.iks.data.jooq.tables.records.DetalleAnulacionRecord, com.iks.data.jooq.tables.records.EmpresasRecord> DA_FK_EMP = ForeignKeys0.DA_FK_EMP;
	public static final org.jooq.ForeignKey<com.iks.data.jooq.tables.records.DetalleTransaccionRecord, com.iks.data.jooq.tables.records.EmpresasRecord> DT_FK_EMP = ForeignKeys0.DT_FK_EMP;
	public static final org.jooq.ForeignKey<com.iks.data.jooq.tables.records.DetalleTransaccionRecord, com.iks.data.jooq.tables.records.CabeceraIkasRecord> DT_FK_CT = ForeignKeys0.DT_FK_CT;
	public static final org.jooq.ForeignKey<com.iks.data.jooq.tables.records.DetalleVentaGasRecord, com.iks.data.jooq.tables.records.CabeceraIkasRecord> DTG_FK_CAB = ForeignKeys0.DTG_FK_CAB;
	public static final org.jooq.ForeignKey<com.iks.data.jooq.tables.records.DetalleVentaGasRecord, com.iks.data.jooq.tables.records.EmpresasRecord> DTG_FK_EMP = ForeignKeys0.DTG_FK_EMP;
	public static final org.jooq.ForeignKey<com.iks.data.jooq.tables.records.LogAuditoriaRecord, com.iks.data.jooq.tables.records.UsuariosRecord> LA_FK_USR = ForeignKeys0.LA_FK_USR;
	public static final org.jooq.ForeignKey<com.iks.data.jooq.tables.records.LogAuditoriaRecord, com.iks.data.jooq.tables.records.TipoOperacionRecord> LA_FK_TPO = ForeignKeys0.LA_FK_TPO;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.iks.data.jooq.tables.records.CabeceraIkasRecord, java.lang.Integer> IDENTITY_CABECERA_IKAS = createIdentity(com.iks.data.jooq.tables.CabeceraIkas.CABECERA_IKAS, com.iks.data.jooq.tables.CabeceraIkas.CABECERA_IKAS.IDCABECERA_IKAS);
		public static org.jooq.Identity<com.iks.data.jooq.tables.records.DetalleAnulacionRecord, java.lang.Integer> IDENTITY_DETALLE_ANULACION = createIdentity(com.iks.data.jooq.tables.DetalleAnulacion.DETALLE_ANULACION, com.iks.data.jooq.tables.DetalleAnulacion.DETALLE_ANULACION.IDDETALLE_ANULACION);
		public static org.jooq.Identity<com.iks.data.jooq.tables.records.DetalleTransaccionRecord, java.lang.Integer> IDENTITY_DETALLE_TRANSACCION = createIdentity(com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION, com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION.ID_DET_TRANSACCION);
		public static org.jooq.Identity<com.iks.data.jooq.tables.records.DetalleVentaGasRecord, java.lang.Integer> IDENTITY_DETALLE_VENTA_GAS = createIdentity(com.iks.data.jooq.tables.DetalleVentaGas.DETALLE_VENTA_GAS, com.iks.data.jooq.tables.DetalleVentaGas.DETALLE_VENTA_GAS.ID_DETALLE_VENTA_GAS);
		public static org.jooq.Identity<com.iks.data.jooq.tables.records.EmpresasRecord, java.lang.Integer> IDENTITY_EMPRESAS = createIdentity(com.iks.data.jooq.tables.Empresas.EMPRESAS, com.iks.data.jooq.tables.Empresas.EMPRESAS.IDEMPRESAS);
		public static org.jooq.Identity<com.iks.data.jooq.tables.records.LogAuditoriaRecord, java.lang.Integer> IDENTITY_LOG_AUDITORIA = createIdentity(com.iks.data.jooq.tables.LogAuditoria.LOG_AUDITORIA, com.iks.data.jooq.tables.LogAuditoria.LOG_AUDITORIA.IDLOG_AUDITORIA);
		public static org.jooq.Identity<com.iks.data.jooq.tables.records.TipoOperacionRecord, java.lang.Integer> IDENTITY_TIPO_OPERACION = createIdentity(com.iks.data.jooq.tables.TipoOperacion.TIPO_OPERACION, com.iks.data.jooq.tables.TipoOperacion.TIPO_OPERACION.IDTIPO_OPERACION);
		public static org.jooq.Identity<com.iks.data.jooq.tables.records.UsuariosRecord, java.lang.Integer> IDENTITY_USUARIOS = createIdentity(com.iks.data.jooq.tables.Usuarios.USUARIOS, com.iks.data.jooq.tables.Usuarios.USUARIOS.ID_USER);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.iks.data.jooq.tables.records.CabeceraIkasRecord> KEY_CABECERA_IKAS_PRIMARY = createUniqueKey(com.iks.data.jooq.tables.CabeceraIkas.CABECERA_IKAS, com.iks.data.jooq.tables.CabeceraIkas.CABECERA_IKAS.IDCABECERA_IKAS);
		public static final org.jooq.UniqueKey<com.iks.data.jooq.tables.records.DetalleAnulacionRecord> KEY_DETALLE_ANULACION_PRIMARY = createUniqueKey(com.iks.data.jooq.tables.DetalleAnulacion.DETALLE_ANULACION, com.iks.data.jooq.tables.DetalleAnulacion.DETALLE_ANULACION.IDDETALLE_ANULACION);
		public static final org.jooq.UniqueKey<com.iks.data.jooq.tables.records.DetalleTransaccionRecord> KEY_DETALLE_TRANSACCION_PRIMARY = createUniqueKey(com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION, com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION.ID_DET_TRANSACCION);
		public static final org.jooq.UniqueKey<com.iks.data.jooq.tables.records.DetalleVentaGasRecord> KEY_DETALLE_VENTA_GAS_PRIMARY = createUniqueKey(com.iks.data.jooq.tables.DetalleVentaGas.DETALLE_VENTA_GAS, com.iks.data.jooq.tables.DetalleVentaGas.DETALLE_VENTA_GAS.ID_DETALLE_VENTA_GAS);
		public static final org.jooq.UniqueKey<com.iks.data.jooq.tables.records.EmpresasRecord> KEY_EMPRESAS_PRIMARY = createUniqueKey(com.iks.data.jooq.tables.Empresas.EMPRESAS, com.iks.data.jooq.tables.Empresas.EMPRESAS.IDEMPRESAS);
		public static final org.jooq.UniqueKey<com.iks.data.jooq.tables.records.LogAuditoriaRecord> KEY_LOG_AUDITORIA_PRIMARY = createUniqueKey(com.iks.data.jooq.tables.LogAuditoria.LOG_AUDITORIA, com.iks.data.jooq.tables.LogAuditoria.LOG_AUDITORIA.IDLOG_AUDITORIA);
		public static final org.jooq.UniqueKey<com.iks.data.jooq.tables.records.TipoOperacionRecord> KEY_TIPO_OPERACION_PRIMARY = createUniqueKey(com.iks.data.jooq.tables.TipoOperacion.TIPO_OPERACION, com.iks.data.jooq.tables.TipoOperacion.TIPO_OPERACION.IDTIPO_OPERACION);
		public static final org.jooq.UniqueKey<com.iks.data.jooq.tables.records.UsuariosRecord> KEY_USUARIOS_PRIMARY = createUniqueKey(com.iks.data.jooq.tables.Usuarios.USUARIOS, com.iks.data.jooq.tables.Usuarios.USUARIOS.ID_USER);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.iks.data.jooq.tables.records.CabeceraIkasRecord, com.iks.data.jooq.tables.records.UsuariosRecord> CI_FK_USR = createForeignKey(com.iks.data.jooq.Keys.KEY_USUARIOS_PRIMARY, com.iks.data.jooq.tables.CabeceraIkas.CABECERA_IKAS, com.iks.data.jooq.tables.CabeceraIkas.CABECERA_IKAS.ID_USUARIO);
		public static final org.jooq.ForeignKey<com.iks.data.jooq.tables.records.CabeceraIkasRecord, com.iks.data.jooq.tables.records.EmpresasRecord> CI_FK_EMP = createForeignKey(com.iks.data.jooq.Keys.KEY_EMPRESAS_PRIMARY, com.iks.data.jooq.tables.CabeceraIkas.CABECERA_IKAS, com.iks.data.jooq.tables.CabeceraIkas.CABECERA_IKAS.ID_EMPRESA);
		public static final org.jooq.ForeignKey<com.iks.data.jooq.tables.records.CabeceraIkasRecord, com.iks.data.jooq.tables.records.TipoOperacionRecord> CI_FK_TPO = createForeignKey(com.iks.data.jooq.Keys.KEY_TIPO_OPERACION_PRIMARY, com.iks.data.jooq.tables.CabeceraIkas.CABECERA_IKAS, com.iks.data.jooq.tables.CabeceraIkas.CABECERA_IKAS.ID_TIPO_OPERACION);
		public static final org.jooq.ForeignKey<com.iks.data.jooq.tables.records.DetalleAnulacionRecord, com.iks.data.jooq.tables.records.EmpresasRecord> DA_FK_EMP = createForeignKey(com.iks.data.jooq.Keys.KEY_EMPRESAS_PRIMARY, com.iks.data.jooq.tables.DetalleAnulacion.DETALLE_ANULACION, com.iks.data.jooq.tables.DetalleAnulacion.DETALLE_ANULACION.ID_EMPRESA);
		public static final org.jooq.ForeignKey<com.iks.data.jooq.tables.records.DetalleTransaccionRecord, com.iks.data.jooq.tables.records.EmpresasRecord> DT_FK_EMP = createForeignKey(com.iks.data.jooq.Keys.KEY_EMPRESAS_PRIMARY, com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION, com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION.ID_EMPRESA);
		public static final org.jooq.ForeignKey<com.iks.data.jooq.tables.records.DetalleTransaccionRecord, com.iks.data.jooq.tables.records.CabeceraIkasRecord> DT_FK_CT = createForeignKey(com.iks.data.jooq.Keys.KEY_CABECERA_IKAS_PRIMARY, com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION, com.iks.data.jooq.tables.DetalleTransaccion.DETALLE_TRANSACCION.ID_CABACERA);
		public static final org.jooq.ForeignKey<com.iks.data.jooq.tables.records.DetalleVentaGasRecord, com.iks.data.jooq.tables.records.CabeceraIkasRecord> DTG_FK_CAB = createForeignKey(com.iks.data.jooq.Keys.KEY_CABECERA_IKAS_PRIMARY, com.iks.data.jooq.tables.DetalleVentaGas.DETALLE_VENTA_GAS, com.iks.data.jooq.tables.DetalleVentaGas.DETALLE_VENTA_GAS.ID_CABECERA);
		public static final org.jooq.ForeignKey<com.iks.data.jooq.tables.records.DetalleVentaGasRecord, com.iks.data.jooq.tables.records.EmpresasRecord> DTG_FK_EMP = createForeignKey(com.iks.data.jooq.Keys.KEY_EMPRESAS_PRIMARY, com.iks.data.jooq.tables.DetalleVentaGas.DETALLE_VENTA_GAS, com.iks.data.jooq.tables.DetalleVentaGas.DETALLE_VENTA_GAS.ID_EMPRESA);
		public static final org.jooq.ForeignKey<com.iks.data.jooq.tables.records.LogAuditoriaRecord, com.iks.data.jooq.tables.records.UsuariosRecord> LA_FK_USR = createForeignKey(com.iks.data.jooq.Keys.KEY_USUARIOS_PRIMARY, com.iks.data.jooq.tables.LogAuditoria.LOG_AUDITORIA, com.iks.data.jooq.tables.LogAuditoria.LOG_AUDITORIA.ID_USUARIO);
		public static final org.jooq.ForeignKey<com.iks.data.jooq.tables.records.LogAuditoriaRecord, com.iks.data.jooq.tables.records.TipoOperacionRecord> LA_FK_TPO = createForeignKey(com.iks.data.jooq.Keys.KEY_TIPO_OPERACION_PRIMARY, com.iks.data.jooq.tables.LogAuditoria.LOG_AUDITORIA, com.iks.data.jooq.tables.LogAuditoria.LOG_AUDITORIA.ID_TIPO_OPERACION);
	}
}
