/**
 * This class is generated by jOOQ
 */
package com.iks.data.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * Tabla de la cabera del proceso de las operaciones de conexion para el sistema 
 * ARCH
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CabeceraIkas extends org.jooq.impl.TableImpl<com.iks.data.jooq.tables.records.CabeceraIkasRecord> {

	private static final long serialVersionUID = 1539500467;

	/**
	 * The singleton instance of <code>ikas.cabecera_ikas</code>
	 */
	public static final com.iks.data.jooq.tables.CabeceraIkas CABECERA_IKAS = new com.iks.data.jooq.tables.CabeceraIkas();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.iks.data.jooq.tables.records.CabeceraIkasRecord> getRecordType() {
		return com.iks.data.jooq.tables.records.CabeceraIkasRecord.class;
	}

	/**
	 * The column <code>ikas.cabecera_ikas.idcabecera_ikas</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.CabeceraIkasRecord, java.lang.Integer> IDCABECERA_IKAS = createField("idcabecera_ikas", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ikas.cabecera_ikas.fecha_carga</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.CabeceraIkasRecord, java.sql.Timestamp> FECHA_CARGA = createField("fecha_carga", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ikas.cabecera_ikas.estado_cabecera</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.CabeceraIkasRecord, java.lang.String> ESTADO_CABECERA = createField("estado_cabecera", org.jooq.impl.SQLDataType.CHAR.length(1).nullable(false), this, "");

	/**
	 * The column <code>ikas.cabecera_ikas.id_usuario</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.CabeceraIkasRecord, java.lang.Integer> ID_USUARIO = createField("id_usuario", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ikas.cabecera_ikas.id_empresa</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.CabeceraIkasRecord, java.lang.Integer> ID_EMPRESA = createField("id_empresa", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ikas.cabecera_ikas.id_tipo_operacion</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.CabeceraIkasRecord, java.lang.Integer> ID_TIPO_OPERACION = createField("id_tipo_operacion", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ikas.cabecera_ikas.fecha_proceso</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.CabeceraIkasRecord, java.sql.Timestamp> FECHA_PROCESO = createField("fecha_proceso", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>ikas.cabecera_ikas</code> table reference
	 */
	public CabeceraIkas() {
		this("cabecera_ikas", null);
	}

	/**
	 * Create an aliased <code>ikas.cabecera_ikas</code> table reference
	 */
	public CabeceraIkas(java.lang.String alias) {
		this(alias, com.iks.data.jooq.tables.CabeceraIkas.CABECERA_IKAS);
	}

	private CabeceraIkas(java.lang.String alias, org.jooq.Table<com.iks.data.jooq.tables.records.CabeceraIkasRecord> aliased) {
		this(alias, aliased, null);
	}

	private CabeceraIkas(java.lang.String alias, org.jooq.Table<com.iks.data.jooq.tables.records.CabeceraIkasRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.iks.data.jooq.Ikas.IKAS, aliased, parameters, "Tabla de la cabera del proceso de las operaciones de conexion para el sistema ARCH");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.iks.data.jooq.tables.records.CabeceraIkasRecord, java.lang.Integer> getIdentity() {
		return com.iks.data.jooq.Keys.IDENTITY_CABECERA_IKAS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.iks.data.jooq.tables.records.CabeceraIkasRecord> getPrimaryKey() {
		return com.iks.data.jooq.Keys.KEY_CABECERA_IKAS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.iks.data.jooq.tables.records.CabeceraIkasRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.iks.data.jooq.tables.records.CabeceraIkasRecord>>asList(com.iks.data.jooq.Keys.KEY_CABECERA_IKAS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.iks.data.jooq.tables.records.CabeceraIkasRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.iks.data.jooq.tables.records.CabeceraIkasRecord, ?>>asList(com.iks.data.jooq.Keys.CI_FK_USR, com.iks.data.jooq.Keys.CI_FK_EMP, com.iks.data.jooq.Keys.CI_FK_TPO);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.iks.data.jooq.tables.CabeceraIkas as(java.lang.String alias) {
		return new com.iks.data.jooq.tables.CabeceraIkas(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.iks.data.jooq.tables.CabeceraIkas rename(java.lang.String name) {
		return new com.iks.data.jooq.tables.CabeceraIkas(name, null);
	}
}
