/**
 * This class is generated by jOOQ
 */
package com.iks.data.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * Tabla de las transacciones de la operacion denominada como Venta GAS
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DetalleVentaGas extends org.jooq.impl.TableImpl<com.iks.data.jooq.tables.records.DetalleVentaGasRecord> {

	private static final long serialVersionUID = -805994015;

	/**
	 * The singleton instance of <code>ikas.detalle_venta_gas</code>
	 */
	public static final com.iks.data.jooq.tables.DetalleVentaGas DETALLE_VENTA_GAS = new com.iks.data.jooq.tables.DetalleVentaGas();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.iks.data.jooq.tables.records.DetalleVentaGasRecord> getRecordType() {
		return com.iks.data.jooq.tables.records.DetalleVentaGasRecord.class;
	}

	/**
	 * The column <code>ikas.detalle_venta_gas.id_detalle_venta_gas</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.DetalleVentaGasRecord, java.lang.Integer> ID_DETALLE_VENTA_GAS = createField("id_detalle_venta_gas", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ikas.detalle_venta_gas.id_cabecera</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.DetalleVentaGasRecord, java.lang.Integer> ID_CABECERA = createField("id_cabecera", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ikas.detalle_venta_gas.terminal</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.DetalleVentaGasRecord, java.lang.String> TERMINAL = createField("terminal", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>ikas.detalle_venta_gas.numeroConfirmacion</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.DetalleVentaGasRecord, java.lang.Double> NUMEROCONFIRMACION = createField("numeroConfirmacion", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * The column <code>ikas.detalle_venta_gas.fecha</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.DetalleVentaGasRecord, java.sql.Date> FECHA = createField("fecha", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>ikas.detalle_venta_gas.id_empresa</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.DetalleVentaGasRecord, java.lang.Integer> ID_EMPRESA = createField("id_empresa", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ikas.detalle_venta_gas.codProducto</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.DetalleVentaGasRecord, java.lang.String> CODPRODUCTO = createField("codProducto", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>ikas.detalle_venta_gas.cantidad</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.DetalleVentaGasRecord, java.lang.Double> CANTIDAD = createField("cantidad", org.jooq.impl.SQLDataType.FLOAT.nullable(false), this, "");

	/**
	 * Create a <code>ikas.detalle_venta_gas</code> table reference
	 */
	public DetalleVentaGas() {
		this("detalle_venta_gas", null);
	}

	/**
	 * Create an aliased <code>ikas.detalle_venta_gas</code> table reference
	 */
	public DetalleVentaGas(java.lang.String alias) {
		this(alias, com.iks.data.jooq.tables.DetalleVentaGas.DETALLE_VENTA_GAS);
	}

	private DetalleVentaGas(java.lang.String alias, org.jooq.Table<com.iks.data.jooq.tables.records.DetalleVentaGasRecord> aliased) {
		this(alias, aliased, null);
	}

	private DetalleVentaGas(java.lang.String alias, org.jooq.Table<com.iks.data.jooq.tables.records.DetalleVentaGasRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.iks.data.jooq.Ikas.IKAS, aliased, parameters, "Tabla de las transacciones de la operacion denominada como Venta GAS");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.iks.data.jooq.tables.records.DetalleVentaGasRecord, java.lang.Integer> getIdentity() {
		return com.iks.data.jooq.Keys.IDENTITY_DETALLE_VENTA_GAS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.iks.data.jooq.tables.records.DetalleVentaGasRecord> getPrimaryKey() {
		return com.iks.data.jooq.Keys.KEY_DETALLE_VENTA_GAS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.iks.data.jooq.tables.records.DetalleVentaGasRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.iks.data.jooq.tables.records.DetalleVentaGasRecord>>asList(com.iks.data.jooq.Keys.KEY_DETALLE_VENTA_GAS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.iks.data.jooq.tables.records.DetalleVentaGasRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.iks.data.jooq.tables.records.DetalleVentaGasRecord, ?>>asList(com.iks.data.jooq.Keys.DTG_FK_CAB, com.iks.data.jooq.Keys.DTG_FK_EMP);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.iks.data.jooq.tables.DetalleVentaGas as(java.lang.String alias) {
		return new com.iks.data.jooq.tables.DetalleVentaGas(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.iks.data.jooq.tables.DetalleVentaGas rename(java.lang.String name) {
		return new com.iks.data.jooq.tables.DetalleVentaGas(name, null);
	}
}
