/**
 * This class is generated by jOOQ
 */
package com.iks.data.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * Tabla que almacena las empresas registrada en el ARCH-STC
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Empresas extends org.jooq.impl.TableImpl<com.iks.data.jooq.tables.records.EmpresasRecord> {

	private static final long serialVersionUID = -965822682;

	/**
	 * The singleton instance of <code>ikas.empresas</code>
	 */
	public static final com.iks.data.jooq.tables.Empresas EMPRESAS = new com.iks.data.jooq.tables.Empresas();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.iks.data.jooq.tables.records.EmpresasRecord> getRecordType() {
		return com.iks.data.jooq.tables.records.EmpresasRecord.class;
	}

	/**
	 * The column <code>ikas.empresas.idempresas</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.EmpresasRecord, java.lang.Integer> IDEMPRESAS = createField("idempresas", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ikas.empresas.codigo_arch</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.EmpresasRecord, java.lang.String> CODIGO_ARCH = createField("codigo_arch", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>ikas.empresas.password_arch</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.EmpresasRecord, byte[]> PASSWORD_ARCH = createField("password_arch", org.jooq.impl.SQLDataType.BLOB.length(65535).nullable(false), this, "");

	/**
	 * The column <code>ikas.empresas.estado</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.EmpresasRecord, java.lang.String> ESTADO = createField("estado", org.jooq.impl.SQLDataType.CHAR.length(1).nullable(false), this, "");

	/**
	 * Create a <code>ikas.empresas</code> table reference
	 */
	public Empresas() {
		this("empresas", null);
	}

	/**
	 * Create an aliased <code>ikas.empresas</code> table reference
	 */
	public Empresas(java.lang.String alias) {
		this(alias, com.iks.data.jooq.tables.Empresas.EMPRESAS);
	}

	private Empresas(java.lang.String alias, org.jooq.Table<com.iks.data.jooq.tables.records.EmpresasRecord> aliased) {
		this(alias, aliased, null);
	}

	private Empresas(java.lang.String alias, org.jooq.Table<com.iks.data.jooq.tables.records.EmpresasRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.iks.data.jooq.Ikas.IKAS, aliased, parameters, "Tabla que almacena las empresas registrada en el ARCH-STC");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.iks.data.jooq.tables.records.EmpresasRecord, java.lang.Integer> getIdentity() {
		return com.iks.data.jooq.Keys.IDENTITY_EMPRESAS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.iks.data.jooq.tables.records.EmpresasRecord> getPrimaryKey() {
		return com.iks.data.jooq.Keys.KEY_EMPRESAS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.iks.data.jooq.tables.records.EmpresasRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.iks.data.jooq.tables.records.EmpresasRecord>>asList(com.iks.data.jooq.Keys.KEY_EMPRESAS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.iks.data.jooq.tables.Empresas as(java.lang.String alias) {
		return new com.iks.data.jooq.tables.Empresas(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.iks.data.jooq.tables.Empresas rename(java.lang.String name) {
		return new com.iks.data.jooq.tables.Empresas(name, null);
	}
}
