/**
 * This class is generated by jOOQ
 */
package com.iks.data.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * tabla de auditoria del sistema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LogAuditoria extends org.jooq.impl.TableImpl<com.iks.data.jooq.tables.records.LogAuditoriaRecord> {

	private static final long serialVersionUID = -1585126720;

	/**
	 * The singleton instance of <code>ikas.log_auditoria</code>
	 */
	public static final com.iks.data.jooq.tables.LogAuditoria LOG_AUDITORIA = new com.iks.data.jooq.tables.LogAuditoria();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.iks.data.jooq.tables.records.LogAuditoriaRecord> getRecordType() {
		return com.iks.data.jooq.tables.records.LogAuditoriaRecord.class;
	}

	/**
	 * The column <code>ikas.log_auditoria.idlog_auditoria</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.LogAuditoriaRecord, java.lang.Integer> IDLOG_AUDITORIA = createField("idlog_auditoria", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ikas.log_auditoria.id_usuario</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.LogAuditoriaRecord, java.lang.Integer> ID_USUARIO = createField("id_usuario", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ikas.log_auditoria.id_row</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.LogAuditoriaRecord, java.lang.String> ID_ROW = createField("id_row", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * The column <code>ikas.log_auditoria.fecha_log</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.LogAuditoriaRecord, java.sql.Timestamp> FECHA_LOG = createField("fecha_log", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ikas.log_auditoria.id_tipo_operacion</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.LogAuditoriaRecord, java.lang.Integer> ID_TIPO_OPERACION = createField("id_tipo_operacion", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>ikas.log_auditoria</code> table reference
	 */
	public LogAuditoria() {
		this("log_auditoria", null);
	}

	/**
	 * Create an aliased <code>ikas.log_auditoria</code> table reference
	 */
	public LogAuditoria(java.lang.String alias) {
		this(alias, com.iks.data.jooq.tables.LogAuditoria.LOG_AUDITORIA);
	}

	private LogAuditoria(java.lang.String alias, org.jooq.Table<com.iks.data.jooq.tables.records.LogAuditoriaRecord> aliased) {
		this(alias, aliased, null);
	}

	private LogAuditoria(java.lang.String alias, org.jooq.Table<com.iks.data.jooq.tables.records.LogAuditoriaRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.iks.data.jooq.Ikas.IKAS, aliased, parameters, "tabla de auditoria del sistema");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.iks.data.jooq.tables.records.LogAuditoriaRecord, java.lang.Integer> getIdentity() {
		return com.iks.data.jooq.Keys.IDENTITY_LOG_AUDITORIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.iks.data.jooq.tables.records.LogAuditoriaRecord> getPrimaryKey() {
		return com.iks.data.jooq.Keys.KEY_LOG_AUDITORIA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.iks.data.jooq.tables.records.LogAuditoriaRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.iks.data.jooq.tables.records.LogAuditoriaRecord>>asList(com.iks.data.jooq.Keys.KEY_LOG_AUDITORIA_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.iks.data.jooq.tables.records.LogAuditoriaRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.iks.data.jooq.tables.records.LogAuditoriaRecord, ?>>asList(com.iks.data.jooq.Keys.LA_FK_USR, com.iks.data.jooq.Keys.LA_FK_TPO);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.iks.data.jooq.tables.LogAuditoria as(java.lang.String alias) {
		return new com.iks.data.jooq.tables.LogAuditoria(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.iks.data.jooq.tables.LogAuditoria rename(java.lang.String name) {
		return new com.iks.data.jooq.tables.LogAuditoria(name, null);
	}
}
