/**
 * This class is generated by jOOQ
 */
package com.iks.data.jooq.tables;

/**
 * This class is generated by jOOQ.
 *
 * Tabla de los usuarios del sistema iKas
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Usuarios extends org.jooq.impl.TableImpl<com.iks.data.jooq.tables.records.UsuariosRecord> {

	private static final long serialVersionUID = 1704277192;

	/**
	 * The singleton instance of <code>ikas.usuarios</code>
	 */
	public static final com.iks.data.jooq.tables.Usuarios USUARIOS = new com.iks.data.jooq.tables.Usuarios();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.iks.data.jooq.tables.records.UsuariosRecord> getRecordType() {
		return com.iks.data.jooq.tables.records.UsuariosRecord.class;
	}

	/**
	 * The column <code>ikas.usuarios.id_user</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.UsuariosRecord, java.lang.Integer> ID_USER = createField("id_user", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ikas.usuarios.nombre</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.UsuariosRecord, java.lang.String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>ikas.usuarios.nickname</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.UsuariosRecord, java.lang.String> NICKNAME = createField("nickname", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>ikas.usuarios.password</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.UsuariosRecord, byte[]> PASSWORD = createField("password", org.jooq.impl.SQLDataType.BLOB.length(65535).nullable(false), this, "");

	/**
	 * The column <code>ikas.usuarios.estado</code>.
	 */
	public final org.jooq.TableField<com.iks.data.jooq.tables.records.UsuariosRecord, java.lang.String> ESTADO = createField("estado", org.jooq.impl.SQLDataType.CHAR.length(1).nullable(false), this, "");

	/**
	 * Create a <code>ikas.usuarios</code> table reference
	 */
	public Usuarios() {
		this("usuarios", null);
	}

	/**
	 * Create an aliased <code>ikas.usuarios</code> table reference
	 */
	public Usuarios(java.lang.String alias) {
		this(alias, com.iks.data.jooq.tables.Usuarios.USUARIOS);
	}

	private Usuarios(java.lang.String alias, org.jooq.Table<com.iks.data.jooq.tables.records.UsuariosRecord> aliased) {
		this(alias, aliased, null);
	}

	private Usuarios(java.lang.String alias, org.jooq.Table<com.iks.data.jooq.tables.records.UsuariosRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.iks.data.jooq.Ikas.IKAS, aliased, parameters, "Tabla de los usuarios del sistema iKas");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.iks.data.jooq.tables.records.UsuariosRecord, java.lang.Integer> getIdentity() {
		return com.iks.data.jooq.Keys.IDENTITY_USUARIOS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.iks.data.jooq.tables.records.UsuariosRecord> getPrimaryKey() {
		return com.iks.data.jooq.Keys.KEY_USUARIOS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.iks.data.jooq.tables.records.UsuariosRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.iks.data.jooq.tables.records.UsuariosRecord>>asList(com.iks.data.jooq.Keys.KEY_USUARIOS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.iks.data.jooq.tables.Usuarios as(java.lang.String alias) {
		return new com.iks.data.jooq.tables.Usuarios(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.iks.data.jooq.tables.Usuarios rename(java.lang.String name) {
		return new com.iks.data.jooq.tables.Usuarios(name, null);
	}
}
